### ISSUE TITLE
Allow adding container dependencies for Async minion container from ensemble

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks-testcontainers-go#10]
See https://github.com/microcks/microcks-testcontainers-java/issues/30 which has the full context and explanations.

Please discuss here the specific issue of adapting and implementing this to Go.

**Comment by JulienBreux** [comment]
Not accurate for Go ?
(because actually nothing is in realtime)

**Comment by lbroudoux** [comment]
Yes I wonder if this is not specific to Java where the lifecycle of testcontainers (create / start / stop). is actually managed by the Spring Boot or Quarkus frameworks. It looks like - correct me if I'm wrong - we don't have such advanced in Go Lang. Closing this issue but feel free to re-open if I missed something.
