### ISSUE TITLE
Update Test container go to v0.31

### ISSUE THREAD

**Issue by oliviernguyenquoc** [microcks/microcks-testcontainers-go#28]
### Reason/Context

Fixe bug in tests

### Description

Just saying that Test container go have release v0.31: https://github.com/testcontainers/testcontainers-go/releases/tag/v0.31.0

It fixes bug you mention: https://github.com/microcks/microcks-testcontainers-go-demo/blob/60df21fe221e06c4adc8f1bef99d87c56db5cab9/internal/controller/order_controller_test.go#L50-L51

### Implementation ideas

I guess you just need to update depedencies

**Comment by JulienBreux** [comment]
@lbroudoux could you close in favor of https://github.com/microcks/microcks-testcontainers-go/issues/30

**Comment by lbroudoux** [comment]
Closing this one in favor of #30.
