### ISSUE TITLE
Update Test container go to v0.32.0

### ISSUE THREAD

**Issue by JulienBreux** [microcks/microcks-testcontainers-go#30]
### Reason/Context

- Related to: https://github.com/testcontainers/testcontainers-go/pull/2551

### Description

We're waiting for v0.32.0 of TC-Go.

**Comment by oliviernguyenquoc** [comment]
Just read this issue. TC-Go v0.32 is finally out: https://github.com/testcontainers/testcontainers-go/releases/tag/v0.32.0
